name: Packer Build CI

on:
  push:
    branches: ["A04-01"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    name: packer-build
    runs-on: ubuntu-latest

    env:
      MYSQL_USERNAME: ${{ secrets.DB_USERNAME }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Zip File
        run: |
          zip -r webapp-demo.zip .

      - name: List Files
        run: ls -al

      - name: Upload Zip File
        uses: actions/upload-artifact@v3
        with:
          name: webapp zip creation
          path: webapp-demo.zip

      - name: Move Zip file to Packer Folder
        run: |
          ls
          pwd
          sudo mv /home/runner/work/webapp/webapp/webapp-demo.zip /home/runner/work/webapp/webapp/packer/

      - name: Run Packer
        run: |
          # Install Packer
          curl -fsSL https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          ls
          pwd
          cd packer_folder
          packer init img-creation.pkr.hcl

          packer build
              -var "aws_region=${{ secrets.AWS_REGION }}" \
              -var "subnet_id=${{ secrets.SUBNET_ID }}" \
              -var "source_ami=${{ secrets.SOURCE_AMI }}" \
              -var "dev_user=${{ secrets.DEV_USER }}" \
              -var "demo_user=${{ secrets.DEMO_USER }}" \
              -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
              -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
              -var "db_username=${{ secrets.DB_USERNAME }}" \
              -var "db_password=${{ secrets.DB_PASSWORD }}" \
              -var "db_database=${{ secrets.DB_DATABASE }}" \
              img-creation.pkr.hcl
  