name: Packer AWS Build

on:
  push:
    branches:
      - main # ✅ Runs only when a PR is merged into main

jobs:
  validate:
    name: Ensure Packer Validation Passed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2

      - name: Initialize Packer (Install Plugins)
        run: packer init .

      - name: Format Packer Template
        run: packer fmt -recursive .

      - name: Validate Packer Template
        run: |
          packer validate \
          -var "aws_region=${{ secrets.AWS_REGION }}" \
          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
          -var "source_ami=${{ secrets.SOURCE_AMI }}" \
          -var "dev_user=${{ secrets.DEV_USER }}" \
          -var "demo_user=${{ secrets.DEMO_USER }}" \
          -var "access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var "secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
          -var "db_username=${{ secrets.DB_USERNAME }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}" \
          -var "db_database=${{ secrets.DB_DATABASE }}" \
          -var "vpc_id=${{ secrets.VPC_ID }}" \
          img-creation.pkr.hcl

  build:
    name: Build Packer Image on AWS
    runs-on: ubuntu-latest
    needs: validate # ✅ Ensures validation job runs first

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      DEV_USER: ${{ secrets.DEV_USER }}
      DEMO_USER: ${{ secrets.DEMO_USER }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      VPC_ID: ${{ secrets.VPC_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2

      - name: Initialize Packer
        run: packer init .

      - name: Build AWS Packer Image
        run: |
          packer build \
          -var "aws_region=${{ env.AWS_REGION }}" \
          -var "subnet_id=${{ env.SUBNET_ID }}" \
          -var "source_ami=${{ env.SOURCE_AMI }}" \
          -var "dev_user=${{ env.DEV_USER }}" \
          -var "demo_user=${{ env.DEMO_USER }}" \
          -var "access_key=${{ env.AWS_ACCESS_KEY }}" \
          -var "secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
          -var "security_group_id=${{ env.SECURITY_GROUP_ID }}" \
          -var "db_username=${{ env.DB_USERNAME }}" \
          -var "db_password=${{ env.DB_PASSWORD }}" \
          -var "db_database=${{ env.DB_DATABASE }}" \
          -var "vpc_id=${{ env.VPC_ID }}" \
          img-creation.pkr.hcl
