name: Packer Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: packer-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.9.4"

      - name: Debug Directory Structure Before
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Create Zip File
        run: |
          # Create zip excluding the packer directory and other unnecessary files
          zip -r webapp.zip . -x "packer/*" "*.git*" "*node_modules*" "*logs*" "*temp*"

      - name: Move Files to Packer Directory
        run: |
          # Move the zip file to packer directory
          mv webapp.zip packer/

      - name: Debug Directory Structure After
        run: |
          echo "Final directory structure:"
          ls -R

      - name: Initialize Packer
        working-directory: ./packer
        run: |
          packer init .
          packer fmt -recursive .

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

        working-directory: ./packer
        run: |
          echo "Checking if img-creation.pkr.hcl exists in packer directory..."
          ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }

          packer build \
          -var "aws_region=$AWS_DEFAULT_REGION" \
          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
          -var "source_ami=${{ secrets.SOURCE_AMI }}" \
          -var "dev_user=${{ secrets.DEV_USER }}" \
          -var "demo_user=${{ secrets.DEMO_USER }}" \
          -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
          -var "vpc_id=${{ secrets.VPC_ID }}" \
          img-creation.pkr.hcl

      - name: Verify AMI Creation
        run: |
          aws ec2 describe-images \
            --owners self \
            --filters "Name=name,Values=CSYE6225*" \
            --query 'Images[*].[ImageId,State,CreationDate]' \
            --output table
