name: Packer Build CI

on:
  push:
    branches: ["main"] # ✅ Runs only when a PR is merged into main

jobs:
  build:
    name: packer-build
    runs-on: ubuntu-latest

    env:
      MYSQL_USERNAME: ${{ secrets.DB_USERNAME }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      DEV_USER: ${{ secrets.DEV_USER }}
      DEMO_USER: ${{ secrets.DEMO_USER }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
      VPC_ID: ${{ secrets.VPC_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI (Official Installer)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Configure AWS CLI for DEV Profile
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config

      - name: Create Zip File of WebApp
        run: |
          zip -r webapp.zip .

      - name: List Files
        run: ls -al

      - name: Upload Zip File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp zip creation
          path: webapp.zip

      - name: Move Zip File to Packer Folder
        run: |
          mkdir -p packer
          mv webapp.zip packer/

      - name: Install System Dependencies (MySQL, unzip, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server unzip

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql
          mysql --version

      - name: Run Packer Build
        run: |
          cd packer
          packer build \
            -var "aws_region=${{ env.AWS_REGION }}" \
            -var "subnet_id=${{ env.SUBNET_ID }}" \
            -var "source_ami=${{ env.SOURCE_AMI }}" \
            -var "dev_user=${{ env.DEV_USER }}" \
            -var "demo_user=${{ env.DEMO_USER }}" \
            -var "aws_access_key=${{ env.AWS_ACCESS_KEY }}" \
            -var "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
            -var "security_group_id=${{ env.SECURITY_GROUP_ID }}" \
            -var "vpc_id=${{ env.VPC_ID }}" \
            webapp.pkr.hcl

      - name: Verify AMI Creation
        run: |
          aws ec2 describe-images \
            --owners self \
            --filters "Name=name,Values=CSYE6225*" \
            --query 'Images[*].[ImageId,State,CreationDate]' \
            --output table
