name: Packer AWS Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Packer Configuration #
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      DEV_USER: ${{ secrets.DEV_USER }}
      DEMO_USER: ${{ secrets.DEMO_USER }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      VPC_ID: ${{ secrets.VPC_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      

      - name: Ensure `setup.sh` Exists in `scripts/` Folder
        run: |
          if [ ! -f packer/scripts/setup.sh ]; then
            echo "ERROR: scripts/setup.sh file is missing!"
            exit 1
          fi

      - name: Install Zip Utility
        run: |
          sudo apt-get install -y zip

      - name: Create WebApp Zip File
        run: |
          zip -r webapp.zip . -x "*.git*" "*node_modules*" "*logs*" "*temp*"

      - name: Debug - Check WebApp Zip File
        run: |
          if [ ! -f webapp.zip ]; then
            echo "ERROR: webapp.zip file is missing!"
            exit 1
          fi
          ls -al

      - name: Install Packer
        uses: hashicorp/setup-packer@v2

      - name: Packer Initialize and Validate
        working-directory: ./packer
        run: |
          packer init .
          packer fmt -recursive .

          # Ensure variables file exists
          if [ ! -f variables.pkrvars.hcl ]; then
            echo "ERROR: variables.pkrvars.hcl file is missing!"
            exit 1
          fi

          # Validate using the variable file
          packer validate -var-file=variables.pkrvars.hcl img-creation.pkr.hcl

      - name: Validation Results Upload #
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: packer/validation.log
