name: Packer Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: packer-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.9.4"

      - name: Debug Directory Structure Before
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Create Zip File
        run: |
          # Create zip excluding the packer directory and other unnecessary files
          zip -r webapp.zip . -x "packer/*" "*.git*" "*node_modules*" "*logs*" "*temp*"

      - name: Move Files to Packer Directory
        run: |
          # Move the zip file to packer directory
          mv webapp.zip packer/

      - name: Debug Directory Structure After
        run: |
          echo "Final directory structure:"
          ls -R

      - name: Initialize Packer
        working-directory: ./packer
        run: |
          packer init .
          packer fmt -recursive .

      # - name: Configure AWS Credentials

      #   working-directory: ./packer
      #   run: |
      #     echo "Checking if img-creation.pkr.hcl exists in packer directory..."
      #     ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }

      #     packer build \
      #     -var "aws_region=$AWS_DEFAULT_REGION" \
      #     -var "access_key=${{ secrets.aws_access_key }}" \
      #     -var "secret_key=${{ secrets.aws_secret_key }}" \}
      #     -var "subnet_id=${{ secrets.SUBNET_ID }}" \
      #     -var "source_ami=${{ secrets.SOURCE_AMI }}" \
      #     -var "dev_user=${{ secrets.DEV_USER }}" \
      #     -var "demo_user=${{ secrets.DEMO_USER }}" \
      #     -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
      #     -var "vpc_id=${{ secrets.VPC_ID }}" \
      #     img-creation.pkr.hcl

      # - name: Configure AWS Credentials
      #   # working-directory: ./packer
      #   # run: |
      #   #   echo "Checking if img-creation.pkr.hcl exists in packer directory..."
      #   #   ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }

      #   #   packer build \
      #   #   -var "aws_region=${{ secrets.AWS_REGION }}" \
      #   #   -var "access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
      #   #   -var "secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
      #   #   -var "subnet_id=${{ secrets.SUBNET_ID }}" \
      #   #   -var "source_ami=${{ secrets.SOURCE_AMI }}" \
      #   #   -var "dev_user=${{ secrets.DEV_USER }}" \
      #   #   -var "demo_user=${{ secrets.DEMO_USER }}" \
      #   #   -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
      #   #   -var "vpc_id=${{ secrets.VPC_ID }}" \
      #   #   img-creation.pkr.hcl
      #   working-directory: ./packer
      #   run: |
      #     echo "Checking if img-creation.pkr.hcl exists in packer directory..."
      #     ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }

      #     packer build\
      #     -var-file=variables.pkrvars.hcl \
      #     -var "aws_region=${{ secrets.AWS_REGION }}" \
      #     -var "access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
      #     -var "secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
      #     -var "subnet_id=${{ secrets.SUBNET_ID }}" \
      #     -var "source_ami=${{ secrets.SOURCE_AMI }}" \
      #     -var "dev_user=${{ secrets.DEV_USER }}" \
      #     -var "demo_user=${{ secrets.DEMO_USER }}" \
      #     -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
      #     -var "vpc_id=${{ secrets.VPC_ID }}" \
      #     img-creation.pkr.hcl

      - name: Create Packer Variable File
        working-directory: ./packer
        run: |
          cat > variables.pkrvars.hcl <<EOF
          aws_region = "${{ secrets.AWS_REGION }}"
          access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          subnet_id = "${{ secrets.SUBNET_ID }}"
          source_ami = "${{ secrets.SOURCE_AMI }}"
          dev_user = "${{ secrets.DEV_USER }}"
          demo_user = "${{ secrets.DEMO_USER }}"
          security_group_id = "${{ secrets.SECURITY_GROUP_ID }}"
          vpc_id = "${{ secrets.VPC_ID }}"
          db_username = "${{ secrets.DB_USERNAME }}"
          db_password = "${{ secrets.DB_PASSWORD }}"
          db_database = "${{ secrets.DB_DATABASE }}"
          EOF

      - name: Configure AWS Credentials
        working-directory: ./packer
        run: |
          echo "Checking if img-creation.pkr.hcl exists in packer directory..."
          ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }

          packer build \
          -var-file=variables.pkrvars.hcl \
          img-creation.pkr.hcl

      - name: Verify AMI Creation
        run: |
          aws ec2 describe-images \
            --owners self \
            --filters "Name=name,Values=CSYE6225*" \
            --query 'Images[*].[ImageId,State,CreationDate]' \
            --output table
