name: Packer Build CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: packer-build
    runs-on: ubuntu-latest

    env:
      MYSQL_USERNAME: ${{ secrets.DB_USERNAME }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Zip File
        run: |
          zip -r webapp-demo.zip .

      - name: List Files
        run: ls -al

      - name: Upload Zip File
        uses: actions/upload-artifact@v4
        with:
          name: webapp zip creation
          path: webapp-demo.zip

      # - name: Move Zip file to Packer Folder
      #   run: |
      #     ls
      #     pwd
      #     sudo mv /home/runner/work/webapp/webapp/webapp-demo.zip /home/runner/work/webapp/webapp/packer/

      - name: Move Zip file to Packer Folder
        run: |
          mkdir -p /home/runner/work/webapp/webapp/packer/
          ls -al /home/runner/work/webapp/webapp/
          mv /home/runner/work/webapp/webapp/webapp-demo.zip /home/runner/work/webapp/webapp/packer/

      - name: Install Packer
        run: |
          # Ensure the old Packer installation is fully removed
          if [ -d "/usr/local/bin/packer" ]; then
            echo "Removing old Packer directory..."
            sudo rm -rf /usr/local/bin/packer
          elif [ -f "/usr/local/bin/packer" ]; then
            echo "Removing old Packer binary..."
            sudo rm -f /usr/local/bin/packer
          fi

          # Create a temporary directory for Packer extraction
          mkdir -p /tmp/packer-install
          cd /tmp/packer-install

          # Download and extract Packer
          curl -fsSL -o packer.zip https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
          unzip -o packer.zip || (echo "Packer extraction failed!" && exit 1)

          # Ensure the binary is executable
          chmod +x packer

          # Move the new Packer binary to the correct location
          sudo mv -f packer /usr/local/bin/packer

          # Verify installation
          packer --version

          # Cleanup
          cd ~
          rm -rf /tmp/packer-install

      - name: Run Packer
        run: |
          # Install Packer
          curl -fsSL https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          ls
          pwd
          cd packer_folder
          packer init img-creation.pkr.hcl

          packer build
              -var "aws_region=${{ secrets.AWS_REGION }}" \
              -var "subnet_id=${{ secrets.SUBNET_ID }}" \
              -var "source_ami=${{ secrets.SOURCE_AMI }}" \
              -var "dev_user=${{ secrets.DEV_USER }}" \
              -var "demo_user=${{ secrets.DEMO_USER }}" \
              -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
              -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
              -var "db_username=${{ secrets.DB_USERNAME }}" \
              -var "db_password=${{ secrets.DB_PASSWORD }}" \
              -var "db_database=${{ secrets.DB_DATABASE }}" \
              img-creation.pkr.hcl
