name: Packer Build CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: packer-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Zip File
        run: |
          zip -r webapp.zip .
          cp webapp.zip packer/

      - name: List Files
        run: ls -al

      - name: Upload Zip File
        uses: actions/upload-artifact@v4
        with:
          name: webapp zip creation
          path: webapp.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Packer
        run: |
          # Install Packer
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install packer -y

          ls
          cd packer
          packer init img-creation.pkr.hcl

          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.SUBNET_ID }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "dev_user=${{ secrets.DEV_USER }}" \
            -var "demo_user=${{ secrets.DEMO_USER }}" \
            -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
            -var "db_username=${{ secrets.DB_EC2_USER }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "db_database=${{ secrets.DB_DATABASE }}" \
            -var "server_port=${{ secrets.SERVER_PORT }}" \
            -var "db_host=${{ secrets.DB_HOST }}" \
            img-creation.pkr.hcl

      # # Extract the AMI ID from the packer build output
      # AMI_ID=$(grep -o 'AMI: ami-[a-z0-9]*' packer_output.log | head -n1 | cut -d' ' -f2)
      # echo "Built AMI ID: $AMI_ID"
      # echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Get Latest AMI ID
        id: ami_id
        run: |
          AMI_ID=$(grep -o 'AMI: ami-[a-z0-9]*' packer_output.log | head -n1 | cut -d' ' -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT

      - name: Reconfigure AWS CLI for DEMO Account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create New Launch Template Version
        id: create_lt_version
        run: |
          echo "Creating new launch template version with AMI ${AMI_ID}..."
          output=$(aws ec2 create-launch-template-version \
            --launch-template-id ${{ secrets.LAUNCH_TEMPLATE_ID }} \
            --source-version 1 \
            --launch-template-data "{\"ImageId\": \"${AMI_ID}\"}" \
            --query 'LaunchTemplateVersion.VersionNumber' \
          )
          echo "Launch template version creation output: $output"
          NEW_VERSION=$(echo "$output" | jq -r '.')
          echo "New launch template version: ${NEW_VERSION}"
          echo "NEW_LAUNCH_TEMPLATE_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      # - name: Update Auto Scaling Group to Use Latest Launch Template
      #   run: |
      #     echo "Updating auto scaling group ${{ secrets.ASG_NAME }} to use launch template version ${NEW_LAUNCH_TEMPLATE_VERSION}..."
      #     aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${{ secrets.ASG_NAME }} --launch-template "LaunchTemplateName=${{ secrets.LAUNCH_TEMPLATE_NAME }},Version=${NEW_LAUNCH_TEMPLATE_VERSION}"

      - name: Update Auto Scaling Group to Use Latest Launch Template Version
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
            --launch-template "LaunchTemplateId=${{ secrets.LAUNCH_TEMPLATE_ID }},Version=${{ steps.lt_version.outputs.version }}"

      - name: Start Instance Refresh
        id: refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
            --query 'InstanceRefreshId' \
            --output text)
          echo "refresh_id=$REFRESH_ID" >> $GITHUB_OUTPUT

      - name: Wait for Instance Refresh to Complete
        run: |
          STATUS=""
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
              --instance-refresh-ids ${{ steps.refresh.outputs.refresh_id }} \
              --query 'InstanceRefreshes[0].Status' \
              --output text)

            echo "Current status: $STATUS"
            if [[ "$STATUS" == "Successful" ]]; then
              echo "Instance refresh completed successfully."
              break
            elif [[ "$STATUS" == "Cancelled" || "$STATUS" == "Failed" ]]; then
              echo "Instance refresh failed or was cancelled."
              exit 1
            fi
            sleep 30
          done
