name: Packer AWS Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Packer Configuration #
    runs-on: ubuntu-latest

    # env:
    #   AWS_REGION: ${{ secrets.AWS_REGION }}
    #   SUBNET_ID: ${{ secrets.SUBNET_ID }}
    #   SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
    #   DEV_USER: ${{ secrets.DEV_USER }}
    #   DEMO_USER: ${{ secrets.DEMO_USER }}
    #   AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
    #   DB_USERNAME: ${{ secrets.DB_USERNAME }}
    #   DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #   DB_DATABASE: ${{ secrets.DB_DATABASE }}
    #   VPC_ID: ${{ secrets.VPC_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure `setup.sh` Exists in `scripts/` Folder
        run: |
          if [ ! -f scripts/setup.sh ]; then
            echo "ERROR: scripts/setup.sh file is missing!"
            exit 1
          fi

      - name: Install Zip Utility
        run: |
          sudo apt-get install -y zip

      - name: Create WebApp Zip File
        run: |
          zip -r webapp-demo.zip . -x "*.git*" "*node_modules*" "*logs*" "*temp*"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug - Check WebApp Zip File
        run: |
          if [ ! -f webapp-demo.zip ]; then
            echo "ERROR: webapp-demo.zip file is missing!"
            exit 1
          fi
          ls -al

      - name: Install Packer
        uses: hashicorp/setup-packer@v2

      - name: Create Packer Variable File
        working-directory: ./packer
        run: |
          cat <<EOF > variables.pkrvars.hcl
          aws_region       = "${{ secrets.AWS_REGION }}"
          access_key       = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          secret_key       = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          subnet_id        = "${{ secrets.SUBNET_ID }}"
          source_ami       = "${{ secrets.SOURCE_AMI }}"
          dev_user         = "${{ secrets.DEV_USER }}"
          demo_user        = "${{ secrets.DEMO_USER }}"
          security_group_id = "${{ secrets.SECURITY_GROUP_ID }}"
          vpc_id           = "${{ secrets.VPC_ID }}"
          EOF

      # - name: Move to Packer Directory and Initialize
      #   run: |
      #     cd packer
      #     packer init .
      #     packer fmt -recursive .
      #     packer validate \
      #     # -var file=variables.pkrvars.hcl \
      #     -var "aws_region=${{ secrets.AWS_REGION }}" \
      #     -var "subnet_id=${{ secrets.SUBNET_ID }}" \
      #     -var "source_ami=${{ secrets.SOURCE_AMI }}" \
      #     -var "dev_user=${{ secrets.DEV_USER }}" \
      #     -var "demo_user=${{ secrets.DEMO_USER }}" \
      #     -var "access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
      #     -var "secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
      #     -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
      #     -var "db_username=${{ secrets.DB_USERNAME }}" \
      #     -var "db_password=${{ secrets.DB_PASSWORD }}" \
      #     -var "db_database=${{ secrets.DB_DATABASE }}" \
      #     -var "vpc_id=${{ secrets.VPC_ID }}" \
      #     img-creation.pkr.hcl

      - name: Move to Packer Directory and Initialize
        working-directory: ./packer
        run: |
          packer init .
          packer fmt -recursive .

          # Ensure variables file exists
          if [ ! -f variables.pkrvars.hcl ]; then
            echo "ERROR: variables.pkrvars.hcl file is missing!"
            exit 1
          fi

          # Validate using the variable file
          packer validate -var-file=variables.pkrvars.hcl img-creation.pkr.hcl

      - name: Validation Results Upload
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: packer/validation.log
