name: Packer VALIDATE

on:
  pull_request:
    branches: ["main"]

jobs:
  packer-ci:
    name: Packer Validation and Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.11.2"

      - name: Run packer init
        run: |
          packer init ./packer/img-creation.pkr.hcl

      # - name: Check CloudWatch Agent Provisioner
      #   run: |
      #     cd packer
      #     if packer inspect img-creation.pkr.hcl | grep -q "amazon-cloudwatch-agent"; then
      #       echo "CloudWatch agent provisioner is present."
      #     else
      #       echo "ERROR: CloudWatch agent provisioner not found!"
      #       exit 1
      #     fi

      - name: Run packer fmt
        id: fmt
        run: |
          cd packer
          packer fmt -check .

      - name: Run packer validate
        id: validate

        run: |
          cd packer
          packer validate img-creation.pkr.hcl
