name: Packer Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: packer-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.9.4"

      - name: Debug Directory Structure Before
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Create Zip File
        run: |
          # Create zip excluding the packer directory and other unnecessary files
          zip -r webapp.zip . -x "packer/*" "*.git*" "*node_modules*" "*logs*" "*temp*"

      - name: Move Files to Packer Directory
        run: |
          # Move the zip file to packer directory
          mv webapp.zip packer/

      - name: Debug Directory Structure After
        run: |
          echo "Final directory structure:"
          ls -R

      - name: Initialize Packer
        working-directory: ./packer
        run: |
          packer init .
          packer fmt -recursive .

      - name: Run Packer Build
        working-directory: ./packer
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.SUBNET_ID }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "dev_user=${{ secrets.DEV_USER }}" \
            -var "demo_user=${{ secrets.DEMO_USER }}" \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
            -var "vpc_id=${{ secrets.VPC_ID }}" \
            img-creation.pkr.hcl

      - name: Verify AMI Creation
        run: |
          aws ec2 describe-images \
            --owners self \
            --filters "Name=name,Values=CSYE6225*" \
            --query 'Images[*].[ImageId,State,CreationDate]' \
            --output table
